---
spec:
  replicas: ${replicas}
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xms128m -Xmx512m -Djava.net.preferIPv4Stack=true"
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: "app=${project.artifactId}"
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: "${project.artifactId}"
              key: apiKey
        name: "${project.artifactId}"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: jgroups-cluster
          protocol: TCP
        - containerPort: 8778
          name: jolokia-port
          protocol: TCP
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz
          initialDelaySeconds: 60
        volumeMounts:
          - name: config
            mountPath: /deployments/config
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.yaml
              path: application.yaml
      serviceAccountName: "${project.artifactId}"